// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: klaussometer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Container2;
lv_obj_t *ui_TempArc1;
lv_obj_t *ui_TempArc2;
lv_obj_t *ui_TempArc3;
lv_obj_t *ui_TempArc4;
lv_obj_t *ui_TempLabel1;
lv_obj_t *ui_TempLabel2;
lv_obj_t *ui_TempLabel3;
lv_obj_t *ui_TempLabel4;
lv_obj_t *ui_RoomName1;
lv_obj_t *ui_RoomName2;
lv_obj_t *ui_RoomName3;
lv_obj_t *ui_RoomName4;
lv_obj_t *ui_StatusMessage;
lv_obj_t *ui_HumidLabel1;
lv_obj_t *ui_HumidLabel3;
lv_obj_t *ui_HumidLabel4;
lv_obj_t *ui_HumidLabel2;
lv_obj_t *ui_Time;
lv_obj_t *ui_TextRooms;
lv_obj_t *ui_TempArcFC;
lv_obj_t *ui_TempLabelFC;
lv_obj_t *ui_TextForecastName;
lv_obj_t *ui_FCConditions;
lv_obj_t *ui_FCWindSpeed;
lv_obj_t *ui_FCUpdateTime;
lv_obj_t *ui_BatteryArc;
lv_obj_t *ui_BatteryLabel;
lv_obj_t *ui_TextBattery;
lv_obj_t *ui_SolarArc;
lv_obj_t *ui_SolarLabel;
lv_obj_t *ui_TextSolar;
lv_obj_t *ui_UsingArc;
lv_obj_t *ui_TextUsing;
lv_obj_t *ui_UsingLabel;
lv_obj_t *ui_ChargingLabel;
lv_obj_t *ui_AsofTimeLabel;
lv_obj_t *ui_ChargingTime;
lv_obj_t *ui_TextKlaussometer;
lv_obj_t *ui_WiFiStatus;
lv_obj_t *ui_ServerStatus;
lv_obj_t *ui_WeatherStatus;
lv_obj_t *ui_SolarStatus;
lv_obj_t *ui_SolarMinMax;
lv_obj_t *ui_GridBought;
lv_obj_t *ui_TempArc5;
lv_obj_t *ui_TempLabel5;
lv_obj_t *ui_RoomName5;
lv_obj_t *ui_FCMin;
lv_obj_t *ui_FCMax;
lv_obj_t *ui_HumidLabel5;
lv_obj_t *ui_Direction1;
lv_obj_t *ui_Direction2;
lv_obj_t *ui_Direction3;
lv_obj_t *ui_Direction4;
lv_obj_t *ui_Direction5;
lv_obj_t *ui_UVArc;
lv_obj_t *ui_UVLabel;
lv_obj_t *ui_TextUV;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
